### ISSUE TITLE
Not an actual issue, just a "thank you" post

### ISSUE THREAD

**Issue by bigkwii** [ShannonHG/krita-spritesheet-generator#1]
I was looking for a way to do this, found the kritaSpriteManager repo, and quickly became annoyed at the fact that it generated the spritesheet with held frames in it. I was just about to implement this by myself but found out through your PR that you already did! I didn't know how to contact you, so I'll just leave this "issue" here. Thank you so much!

**Comment by ShannonHG** [comment]
> I was looking for a way to do this, found the kritaSpriteManager repo, and quickly became annoyed at the fact that it generated the spritesheet with held frames in it. I was just about to implement this by myself but the found out through your PR that you already did! I didn't know how to contact you, so I'll just leave this "issue" here. Thank you so much!

@bigkwii I didn't expect anybody to even discover this repo, so I'm glad to hear that it may be useful to you! Your first sentence is exactly what I went through and is what led me to build this. 

If you find any issues or see areas for improvement don't hesitate to open another issue and let me know!
