### ISSUE TITLE
Need Help Installing ("Configure Krita")

### ISSUE THREAD

**Issue by KaptainKumnt** [ShannonHG/krita-spritesheet-generator#2]
I have a Mac and this is version 5.2.3 of Krita.

I made it to step 7 in the installation process and where I have to go from (Settings -> Configure Krita -> Python Plugin Manager). The only problem is that (for me at least) I can not find (Configure Krita) anywhere. The screenshot attached is what happens when I press settings while Krita is open:
<img width="251" alt="Screenshot 2024-08-18 at 1 58 14 AM" src="https://github.com/user-attachments/assets/827b7d43-cb4a-4574-bbee-ce84ee83557e">

Please help me with this, I really want to replace Adobe and this could really help me out.

**Comment by ShannonHG** [comment]
It seems like the "Configure Krita" option is in a different place on Mac. When you press the "Krita" button in the top left corner (next to the Apple icon) you should be able to find the "Configure Krita" option in the menu that opens. Apparently it may also be nested in a "Preferences" menu but I'm not completely sure. 

Once you find it, if you could let me know exactly where it's at that would be super helpful so I could update the instructions.

**Comment by KaptainKumnt** [comment]
Thanks for the help, I found it exactly where you said it would be: On the Krita button -> Preferences -> Configure Krita.
<img width="166" alt="Screenshot 2024-08-18 at 1 48 01 PM" src="https://github.com/user-attachments/assets/8b85280c-cfef-4c0f-8d0f-21b8fad62a61">
<img width="889" alt="Screenshot 2024-08-18 at 1 48 21 PM" src="https://github.com/user-attachments/assets/942811fa-7766-4165-a7a1-aed6c58ccb26">
I tested it out with a mini animation, kind of disappointed in the fact it doesn't export an XML file like Adobe, but it still does as advertised. But that's besides the point, I found out that when I exported the spritesheet, it also included the onion layered frames. This is done by using the sprite sheet generator while Onion frames are on or off (The lightbulb button while on an animation template). Here's the comparison:
![Spritesheet](https://github.com/user-attachments/assets/5eaf9af2-48e7-4950-9910-849deb0c5d81)
![SpriteshIt](https://github.com/user-attachments/assets/dcdd533b-8fe6-48f6-baaa-529fe7bab819)

Again, thanks for your help and making this awesome tool.

**Comment by ShannonHG** [comment]
> Thanks for the help, I found it exactly where you said it would be: On the Krita button -> Preferences -> Configure Krita.

Perfect, glad you were able to find it there!

> I tested it out with a mini animation, kind of disappointed in the fact it doesn't export an XML file like Adobe, but it still does as advertised.

Ah yeah I didn't realize XML (and JSON) were formats that were being used for spritesheets/texture atlases so I didn't really consider them while making this tool. For the time being I'll probably keep it limited to PNGs (and maybe other basic image types), but if I find that XML/JSON is more commonly used than I thought then I'll reconsider.

> But that's besides the point, I found out that when I exported the spritesheet, it also included the onion layered frames.

I noticed this as well, but unfortunately Krita doesn't seem to have an simple way to detect and disable onion skins through scripting as far as I know. I'll keep looking into it since it's something that's a bit annoying for my workflow as well though.

> Again, thanks for your help and making this awesome tool.

No problem, happy to help!
